### ISSUE TITLE
New Pull Request with improvements

### ISSUE THREAD

**Issue by ignabelitzky** [khanshaib11/DSA-Data-Graph-Project#2]
I just made a Pull Request with improvements in the code. (Refactoring and Restructuration of the directory).

Link to the PR: https://github.com/khanshaib11/DSA-Data-Graph-Project/pull/1

Hope you like it and approve it!

**Comment by khanshaib11** [comment]
Thanks , i am new to git and doesn't know much about git , but learning never ends.

**Comment by khanshaib11** [comment]
Thank you so much for your time and contribution.
